In [21]:
from setup import setup_notebook
setup_notebook()
from importlib import reload

from spectraldb.utils.types import Wavelength, Color
from spectraldb.models.wss import WSS
from spectraldb.utils.io import demo_data
from spectraldb.utils.misc import select_random_wavelengths
from spectraldb.colorspaces import XYZ_to_sRGB, sRGB_to_XYZ
import spectraldb.colorspaces as cs
reload(cs)
import spectraldb.colorspaces as cs

import spectraldb.chromaticadaptation as ca
reload(ca)
import spectraldb.chromaticadaptation as ca

import spectraldb.illuminant as ill
argon = demo_data()
argon.head()

illE = ill.get_illuminant("E")
illE

ca.adapt(ill.get_illuminant("A").to_CIE_XYZ(), "B", "vonkries", src_ill="A")


[[ 0.9574884  -0.16436131  0.29023557]
 [-0.01805395  1.01853793  0.00363723]
 [ 0.          0.          2.39491354]]


CIE_XYZ(x=np.float64(0.9907200236868112), y=np.float64(0.9999999754545796), z=np.float64(0.8522299819259063), deg=None)

In [13]:

wave = select_random_wavelengths(argon)
print(wave)
XYZ = WSS.fit(wave)
print(XYZ)

ca.adapt(XYZ, "A", "bradford")


Wavelength(wl=598.8288, srgb=None, xyz=None, illuminant=None)
CIE_XYZ(x=np.float64(1.0555917990742638), y=np.float64(0.6497160204760852), z=np.float64(4.901448270813297e-05), deg=2)


CIE_XYZ(x=np.float64(1.2725369003113634), y=np.float64(0.7264243844243851), z=np.float64(-0.0008714363197144384), deg=2)